dist: xenial
language: python
cache:
  pip: true
  directories:
    - $HOME/cache/
branches:
  only:
  - master
matrix:
  include:
  - name: Wiki Build
    python: '3.6'
    env: BUILD_FOCUS=WIKI
  - name: Epub Build
    python: '3.6'
    env: BUILD_FOCUS=EPUB
  - name: PDF Build
    python: '3.6'
    env: BUILD_FOCUS=PDF
    addons:
      apt:
        packages:
        - texlive-full
install:
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
- export TRAVIS_EMAIL="build@travis.com"
- export TRAVIS_NAME="Travis CI"
- bash _scripts/install.sh
script:
- bash _scripts/script.sh
before_deploy:
- gpg --passphrase $pradyumna_gpg_passphrase --output /tmp/deploy_site --decrypt pradyumna-website-deploy.enc
- gpg --passphrase $pradyumna_gpg_passphrase --output /tmp/deploy_wiki --decrypt pradyumna-coursebook-deploy.enc
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_wiki
- chmod 600 /tmp/deploy_site
deploy:
  provider: script
  script: bash _scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
